export const UNISWAP_FACTORY_V2_ADDRESS =
  "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
export const CURVE_FACTORY_ADDRESS =
  "0xB9fC157394Af804a3578134A6585C0dc9cc990d4";
export const PAIR_ADDRESS = "0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852";

export const UNISWAP_ABI = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0In",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1In",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0Out",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1Out",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "Swap",
    type: "event",
  },
];

export const CURVE_ABI = [
  {
    name: "TokenExchange",
    inputs: [
      { type: "address", name: "buyer", indexed: true },
      { type: "int128", name: "sold_id", indexed: false },
      { type: "uint256", name: "tokens_sold", indexed: false },
      { type: "int128", name: "bought_id", indexed: false },
      { type: "uint256", name: "tokens_bought", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "AddLiquidity",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[3]", name: "token_amounts", indexed: false },
      { type: "uint256[3]", name: "fees", indexed: false },
      { type: "uint256", name: "invariant", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidity",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[3]", name: "token_amounts", indexed: false },
      { type: "uint256[3]", name: "fees", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidityOne",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256", name: "token_amount", indexed: false },
      { type: "uint256", name: "coin_amount", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RemoveLiquidityImbalance",
    inputs: [
      { type: "address", name: "provider", indexed: true },
      { type: "uint256[3]", name: "token_amounts", indexed: false },
      { type: "uint256[3]", name: "fees", indexed: false },
      { type: "uint256", name: "invariant", indexed: false },
      { type: "uint256", name: "token_supply", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "CommitNewAdmin",
    inputs: [
      { type: "uint256", name: "deadline", indexed: true },
      { type: "address", name: "admin", indexed: true },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "NewAdmin",
    inputs: [{ type: "address", name: "admin", indexed: true }],
    anonymous: false,
    type: "event",
  },
  {
    name: "CommitNewFee",
    inputs: [
      { type: "uint256", name: "deadline", indexed: true },
      { type: "uint256", name: "fee", indexed: false },
      { type: "uint256", name: "admin_fee", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "NewFee",
    inputs: [
      { type: "uint256", name: "fee", indexed: false },
      { type: "uint256", name: "admin_fee", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "RampA",
    inputs: [
      { type: "uint256", name: "old_A", indexed: false },
      { type: "uint256", name: "new_A", indexed: false },
      { type: "uint256", name: "initial_time", indexed: false },
      { type: "uint256", name: "future_time", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "StopRampA",
    inputs: [
      { type: "uint256", name: "A", indexed: false },
      { type: "uint256", name: "t", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    outputs: [],
    inputs: [
      { type: "address", name: "_owner" },
      { type: "address[3]", name: "_coins" },
      { type: "address", name: "_pool_token" },
      { type: "uint256", name: "_A" },
      { type: "uint256", name: "_fee" },
      { type: "uint256", name: "_admin_fee" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    name: "A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 5227,
  },
  {
    name: "get_virtual_price",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 1133537,
  },
  {
    name: "calc_token_amount",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256[3]", name: "amounts" },
      { type: "bool", name: "deposit" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 4508776,
  },
  {
    name: "add_liquidity",
    outputs: [],
    inputs: [
      { type: "uint256[3]", name: "amounts" },
      { type: "uint256", name: "min_mint_amount" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 6954858,
  },
  {
    name: "get_dy",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "int128", name: "i" },
      { type: "int128", name: "j" },
      { type: "uint256", name: "dx" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 2673791,
  },
  {
    name: "get_dy_underlying",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "int128", name: "i" },
      { type: "int128", name: "j" },
      { type: "uint256", name: "dx" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 2673474,
  },
  {
    name: "exchange",
    outputs: [],
    inputs: [
      { type: "int128", name: "i" },
      { type: "int128", name: "j" },
      { type: "uint256", name: "dx" },
      { type: "uint256", name: "min_dy" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 2818066,
  },
  {
    name: "remove_liquidity",
    outputs: [],
    inputs: [
      { type: "uint256", name: "_amount" },
      { type: "uint256[3]", name: "min_amounts" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 192846,
  },
  {
    name: "remove_liquidity_imbalance",
    outputs: [],
    inputs: [
      { type: "uint256[3]", name: "amounts" },
      { type: "uint256", name: "max_burn_amount" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 6951851,
  },
  {
    name: "calc_withdraw_one_coin",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [
      { type: "uint256", name: "_token_amount" },
      { type: "int128", name: "i" },
    ],
    stateMutability: "view",
    type: "function",
    gas: 1102,
  },
  {
    name: "remove_liquidity_one_coin",
    outputs: [],
    inputs: [
      { type: "uint256", name: "_token_amount" },
      { type: "int128", name: "i" },
      { type: "uint256", name: "min_amount" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 4025523,
  },
  {
    name: "ramp_A",
    outputs: [],
    inputs: [
      { type: "uint256", name: "_future_A" },
      { type: "uint256", name: "_future_time" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 151919,
  },
  {
    name: "stop_ramp_A",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 148637,
  },
  {
    name: "commit_new_fee",
    outputs: [],
    inputs: [
      { type: "uint256", name: "new_fee" },
      { type: "uint256", name: "new_admin_fee" },
    ],
    stateMutability: "nonpayable",
    type: "function",
    gas: 110461,
  },
  {
    name: "apply_new_fee",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 97242,
  },
  {
    name: "revert_new_parameters",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 21895,
  },
  {
    name: "commit_transfer_ownership",
    outputs: [],
    inputs: [{ type: "address", name: "_owner" }],
    stateMutability: "nonpayable",
    type: "function",
    gas: 74572,
  },
  {
    name: "apply_transfer_ownership",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 60710,
  },
  {
    name: "revert_transfer_ownership",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 21985,
  },
  {
    name: "admin_balances",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "i" }],
    stateMutability: "view",
    type: "function",
    gas: 3481,
  },
  {
    name: "withdraw_admin_fees",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 21502,
  },
  {
    name: "donate_admin_fees",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 111389,
  },
  {
    name: "kill_me",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 37998,
  },
  {
    name: "unkill_me",
    outputs: [],
    inputs: [],
    stateMutability: "nonpayable",
    type: "function",
    gas: 22135,
  },
  {
    name: "coins",
    outputs: [{ type: "address", name: "" }],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2220,
  },
  {
    name: "balances",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [{ type: "uint256", name: "arg0" }],
    stateMutability: "view",
    type: "function",
    gas: 2250,
  },
  {
    name: "fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2171,
  },
  {
    name: "admin_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2201,
  },
  {
    name: "owner",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2231,
  },
  {
    name: "initial_A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2261,
  },
  {
    name: "future_A",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2291,
  },
  {
    name: "initial_A_time",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2321,
  },
  {
    name: "future_A_time",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2351,
  },
  {
    name: "admin_actions_deadline",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2381,
  },
  {
    name: "transfer_ownership_deadline",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2411,
  },
  {
    name: "future_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2441,
  },
  {
    name: "future_admin_fee",
    outputs: [{ type: "uint256", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2471,
  },
  {
    name: "future_owner",
    outputs: [{ type: "address", name: "" }],
    inputs: [],
    stateMutability: "view",
    type: "function",
    gas: 2501,
  },
];

export const CURVE_FACTORY_ABI = [
  {
    name: "BasePoolAdded",
    inputs: [{ name: "base_pool", type: "address", indexed: false }],
    anonymous: false,
    type: "event",
  },
  {
    name: "PlainPoolDeployed",
    inputs: [
      { name: "coins", type: "address[4]", indexed: false },
      { name: "A", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
      { name: "deployer", type: "address", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "MetaPoolDeployed",
    inputs: [
      { name: "coin", type: "address", indexed: false },
      { name: "base_pool", type: "address", indexed: false },
      { name: "A", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
      { name: "deployer", type: "address", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    name: "LiquidityGaugeDeployed",
    inputs: [
      { name: "pool", type: "address", indexed: false },
      { name: "gauge", type: "address", indexed: false },
    ],
    anonymous: false,
    type: "event",
  },
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [{ name: "_fee_receiver", type: "address" }],
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    name: "metapool_implementations",
    inputs: [{ name: "_base_pool", type: "address" }],
    outputs: [{ name: "", type: "address[10]" }],
    gas: 21716,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "find_pool_for_coins",
    inputs: [
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    name: "find_pool_for_coins",
    inputs: [
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
      { name: "i", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_base_pool",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    gas: 2663,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_n_coins",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    gas: 2699,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_meta_n_coins",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    gas: 5201,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_coins",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address[4]" }],
    gas: 9164,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_underlying_coins",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address[8]" }],
    gas: 21345,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_decimals",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[4]" }],
    gas: 20185,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_underlying_decimals",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[8]" }],
    gas: 19730,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_metapool_rates",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[2]" }],
    gas: 5281,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_balances",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[4]" }],
    gas: 20435,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_underlying_balances",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[8]" }],
    gas: 39733,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_A",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    gas: 3135,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_fees",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    gas: 5821,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_admin_balances",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256[4]" }],
    gas: 13535,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_coin_indices",
    inputs: [
      { name: "_pool", type: "address" },
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
    ],
    outputs: [
      { name: "", type: "int128" },
      { name: "", type: "int128" },
      { name: "", type: "bool" },
    ],
    gas: 33407,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_gauge",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    gas: 3089,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_implementation_address",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    gas: 3119,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "is_meta",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    gas: 3152,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_pool_asset_type",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    gas: 5450,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "get_fee_receiver",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    gas: 5480,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_plain_pool",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
      { name: "_coins", type: "address[4]" },
      { name: "_A", type: "uint256" },
      { name: "_fee", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_plain_pool",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
      { name: "_coins", type: "address[4]" },
      { name: "_A", type: "uint256" },
      { name: "_fee", type: "uint256" },
      { name: "_asset_type", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_plain_pool",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
      { name: "_coins", type: "address[4]" },
      { name: "_A", type: "uint256" },
      { name: "_fee", type: "uint256" },
      { name: "_asset_type", type: "uint256" },
      { name: "_implementation_idx", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_metapool",
    inputs: [
      { name: "_base_pool", type: "address" },
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
      { name: "_coin", type: "address" },
      { name: "_A", type: "uint256" },
      { name: "_fee", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_metapool",
    inputs: [
      { name: "_base_pool", type: "address" },
      { name: "_name", type: "string" },
      { name: "_symbol", type: "string" },
      { name: "_coin", type: "address" },
      { name: "_A", type: "uint256" },
      { name: "_fee", type: "uint256" },
      { name: "_implementation_idx", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "deploy_gauge",
    inputs: [{ name: "_pool", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    gas: 93079,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "add_base_pool",
    inputs: [
      { name: "_base_pool", type: "address" },
      { name: "_fee_receiver", type: "address" },
      { name: "_asset_type", type: "uint256" },
      { name: "_implementations", type: "address[10]" },
    ],
    outputs: [],
    gas: 1206132,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "set_metapool_implementations",
    inputs: [
      { name: "_base_pool", type: "address" },
      { name: "_implementations", type: "address[10]" },
    ],
    outputs: [],
    gas: 382072,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "set_plain_implementations",
    inputs: [
      { name: "_n_coins", type: "uint256" },
      { name: "_implementations", type: "address[10]" },
    ],
    outputs: [],
    gas: 379687,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "set_gauge_implementation",
    inputs: [{ name: "_gauge_implementation", type: "address" }],
    outputs: [],
    gas: 38355,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "batch_set_pool_asset_type",
    inputs: [
      { name: "_pools", type: "address[32]" },
      { name: "_asset_types", type: "uint256[32]" },
    ],
    outputs: [],
    gas: 1139545,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "commit_transfer_ownership",
    inputs: [{ name: "_addr", type: "address" }],
    outputs: [],
    gas: 38415,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "accept_transfer_ownership",
    inputs: [],
    outputs: [],
    gas: 58366,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "set_manager",
    inputs: [{ name: "_manager", type: "address" }],
    outputs: [],
    gas: 40996,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "set_fee_receiver",
    inputs: [
      { name: "_base_pool", type: "address" },
      { name: "_fee_receiver", type: "address" },
    ],
    outputs: [],
    gas: 38770,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "convert_metapool_fees",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    gas: 12880,
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    name: "add_existing_metapools",
    inputs: [{ name: "_pools", type: "address[10]" }],
    outputs: [{ name: "", type: "bool" }],
    gas: 8610792,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    gas: 3438,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "future_admin",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    gas: 3468,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "manager",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    gas: 3498,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "pool_list",
    inputs: [{ name: "arg0", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    gas: 3573,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "pool_count",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    gas: 3558,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "base_pool_list",
    inputs: [{ name: "arg0", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    gas: 3633,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "base_pool_count",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    gas: 3618,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "base_pool_assets",
    inputs: [{ name: "arg0", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    gas: 3863,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "plain_implementations",
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "uint256" },
    ],
    outputs: [{ name: "", type: "address" }],
    gas: 3838,
  },
  {
    stateMutability: "view",
    type: "function",
    name: "gauge_implementation",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    gas: 3708,
  },
];
